// Static requires keep Metro/Expo asset discovery predictable.
export const wordMaizeAssets = {
  corn: {
    core: require('./corn/cob-core.png'),
    fullV2: require('./corn/cob-full-v2.png'),
    huskLeft: require('./corn/husk-left.png'),
    huskRight: require('./corn/husk-right.png'),
    huskBottom: require('./corn/husk-bottom.png'),
  },
  kernels: {
    approvedNormal: require('./corn/asset-set-v1/kernel-full.png'),
    approvedSocket: require('./corn/asset-set-v1/kernel-empty-socket.png'),
    normal: [
      require('./kernels/yellow/kernel-normal-01.png'),
      require('./kernels/yellow/kernel-normal-02.png'),
      require('./kernels/yellow/kernel-normal-03.png'),
    ],
    normalV2: require('./kernels/yellow/kernel-normal-v2.png'),
    kernelV3: require('./kernels/kernel-v3.jpg'),
    selected: require('./kernels/yellow/kernel-selected.png'),
    selectedV2: require('./kernels/yellow/kernel-selected-v2.png'),
    hint: require('./kernels/yellow/kernel-hint.png'),
    hintV2: require('./kernels/yellow/kernel-hint-v2.png'),
    emptySocket: require('./kernels/yellow/kernel-empty-socket.png'),
    emptySocketV2: require('./kernels/yellow/kernel-empty-socket-v2.png'),
    flying: require('./kernels/yellow/kernel-flying.png'),
    varieties: {
      sweet: {
        full: require('./corn/asset-set-v1/kernel-full.png'),
        socket: require('./corn/asset-set-v1/kernel-empty-socket.png'),
      },
      white: {
        full: require('./corn/varieties/white/kernel-full.png'),
        socket: require('./corn/varieties/white/kernel-empty-socket.png'),
      },
      flint: [
        {
          full: require('./corn/varieties/flint-red/kernel-full.png'),
          socket: require('./corn/varieties/flint-red/kernel-empty-socket.png'),
        },
        {
          full: require('./corn/varieties/flint-orange/kernel-full.png'),
          socket: require('./corn/varieties/flint-orange/kernel-empty-socket.png'),
        },
        {
          full: require('./corn/varieties/flint-blue/kernel-full.png'),
          socket: require('./corn/varieties/flint-blue/kernel-empty-socket.png'),
        },
        {
          full: require('./corn/varieties/flint-gold/kernel-full.png'),
          socket: require('./corn/varieties/flint-gold/kernel-empty-socket.png'),
        },
      ],
      flintCrack: require('./corn/varieties/flint/kernel-crack-overlay.png'),
      popcorn: {
        full: require('./corn/varieties/popcorn/kernel-full.png'),
        socket: require('./corn/varieties/popcorn/kernel-empty-socket.png'),
      },
      blue: {
        full: require('./corn/varieties/blue/kernel-full-v2.png'),
        socket: require('./corn/varieties/blue/kernel-empty-socket.png'),
      },
      golden: {
        full: require('./corn/varieties/golden/kernel-full.png'),
        socket: require('./corn/varieties/golden/kernel-empty-socket.png'),
      },
    },
  },
  props: {
    harvestBasket: require('./props/harvest-basket-v2.png'),
    harvestBasketEmpty: require('./props/harvest-basket-empty.png'),
    harvestBasketPartial: require('./props/harvest-basket-partial.png'),
    harvestBasketFull: require('./props/harvest-basket-full.png'),
    tractor: require('./props/tractor-mascot-v2.png'),
    tractorIdle: require('./props/tractor-mascot-v2.png'),
    tractorCelebration: require('./props/tractor-celebration.png'),
    chest: require('./props/golden-chest.png'),
  },
  characters: {
    patchSpeaking: require('./characters/patch-speaking-v1.png'),
    patchIdle: require('./characters/patch-idle.png'),
    patchPointing: require('./characters/patch-pointing.png'),
    patchWorried: require('./characters/patch-worried.png'),
    patchCelebrating: require('./characters/patch-celebrating.png'),
    farmerMayWelcome: require('./characters/farmer-may-welcome.png'),
    farmerMayCelebration: require('./characters/farmer-may-celebration.png'),
    homeFarmerIdle: require('./characters/home-farmer-idle.png'),
  },
  powerups: {
    scarecrow: require('./powerups/scarecrow.png'),
    butterBrush: require('./powerups/butter-brush.png'),
    cornPicker: require('./powerups/corn-picker.png'),
  },
  obstacles: {
    caterpillar: require('./obstacles/caterpillar-kernel-v2.png'),
    crow: require('./obstacles/crow-circling-v2.png'),
    squirrel: require('./obstacles/squirrel-v1.png'),
    weed: require('./obstacles/weed-kernel-v2.png'),
    crowTarget: require('./obstacles/crow-target-v1.png'),
    spiderWeb: require('./obstacles/spider-web-cluster-v1.png'),
    frostKernel: require('./obstacles/frost-kernel-v1.png'),
    web: require('./obstacles/spider-web-cluster-v1.png'),
    frost: require('./obstacles/frost-kernel-v1.png'),
  },
  backgrounds: {
    // Approved kernel-cob demo composition: the supporting cob is painted into
    // the barn scene and the native rotating kernel board sits over its face.
    gameplayApprovedCob: require('../../experiments/kernel-cob-demo/public/assets/gameplay-bg.jpg'),
    gameplayCobByType: {
      sweet: require('../../experiments/kernel-cob-demo/public/assets/gameplay-bg.jpg'),
      white: require('./backgrounds/corn/gameplay-cob-white-v1.png'),
      flint: require('./backgrounds/corn/gameplay-cob-flint-v1.png'),
      popcorn: require('./backgrounds/corn/gameplay-cob-popcorn-v1.png'),
      blue: require('./backgrounds/corn/gameplay-cob-blue-v2.png'),
      golden: require('./backgrounds/corn/gameplay-cob-golden-v1.png'),
    },
    gameplayFarm: require('./backgrounds/gameplay-farm.png'),
    gameplayFarmV2: require('./backgrounds/gameplay-farm-v2.png'),
    gameplayFarmV3: require('./backgrounds/gameplay_bg_v3.jpg'),
    gameplayFarmV4: require('./backgrounds/gameplay_bg_v4.jpg'),
    gameplayFarmV6: require('./backgrounds/gameplay_bg_v6.jpg'),
    gameplayFarmV7: require('./backgrounds/gameplay_bg_v7.jpg'),
    gameplayFarmV8: require('./backgrounds/gameplay_bg_v8.jpg'),
    gameplayCrowCreek: require('./backgrounds/gameplay-crow-creek-v1.png'),
    gameplayOrchardHollow: require('./backgrounds/gameplay-orchard-hollow-v1.png'),
    gameplayMoonlightMaize: require('./backgrounds/gameplay-moonlight-maize-v1.png'),
    mapSweetCorn: require('./backgrounds/map-sweet-corn-v1.png'),
    mapCrowCreek: require('./backgrounds/map-crow-creek-v1.png'),
    mapOrchardHollow: require('./backgrounds/map-orchard-hollow-v1.png'),
    mapMoonlight: require('./backgrounds/map-moonlight-v1.png'),
    homeFarm: require('./backgrounds/home-farm.png'),
    homeFarmUnrestored: require('./backgrounds/home-farm-unrestored.png'),
    homeFarmRestored: require('./backgrounds/home-farm-restored.png'),
    homeHero: require('./backgrounds/home-hero-v1.jpg'),
    worldMap: require('./backgrounds/world-map.png'),
    shopBarn: require('./backgrounds/shop-barn.png'),
  },
  ui: {
    btnHome: require('./ui/btn_home.jpg'),
    btnRotate: require('./ui/btn_rotate.jpg'),
    btnPause: require('./ui/btn-pause.png'),
    btnShuffle: require('./ui/btn-shuffle.png'),
    mapNodeCurrent: require('./ui/map-node-current.png'),
    mapNodeComplete: require('./ui/map-node-complete.png'),
    mapNodeLocked: require('./ui/map-node-locked.png'),
    mapStarEmpty: require('./ui/map-star-empty.png'),
    mapStarFilled: require('./ui/map-star-filled.png'),
    tabFarm: require('./ui/tab-farm.png'),
    tabPlay: require('./ui/tab-play.png'),
    tabShop: require('./ui/tab-shop.png'),
    storeFeature: require('./ui/store-feature.png'),
    btnHeart: require('./ui/btn_heart.jpg'),
    coin: require('./ui/coin-v2.png'),
    energy: require('./ui/energy.png'),
    logo: require('./ui/logo-v2.png'),
    logoCorn: require('./ui/logo-corn.png'),
    logoTaglinePlaque: require('./ui/logo-tagline-plaque.png'),
    homeContinueThumb: require('./ui/home-continue-thumb.png'),
    homeWorldMapThumb: require('./ui/home-world-map-thumb.png'),
    homeWorldThumb: require('./ui/home-world-thumb.png'),
    iconGamepad: require('./ui/icon-gamepad.png'),
    iconFairTent: require('./ui/icon-fair-tent.png'),
    iconHudTime: require('./ui/icon-hud-time.png'),
    iconHudHarvest: require('./ui/icon-hud-harvest.png'),
    iconHudChapter: require('./ui/icon-hud-chapter.png'),
    iconHudFog: require('./ui/icon-hud-fog.png'),
    chapterThumbs: [
      require('./ui/chapter-thumb-01.png'),
      require('./ui/chapter-thumb-02.png'),
      require('./ui/chapter-thumb-03.png'),
      require('./ui/chapter-thumb-04.png'),
      require('./ui/chapter-thumb-05.png'),
      require('./ui/chapter-thumb-06.png'),
      require('./ui/chapter-thumb-07.png'),
      require('./ui/chapter-thumb-08.png'),
    ],
    materials: {
      woodPlanks: require('./ui/materials/wood-planks-tile-v1.png'),
    },
  },
  effects: {
    sparkleBurst: require('./effects/sparkle-burst.png'),
    kernelPop: require('./effects/kernel-pop.png'),
    butterTrail: require('./effects/butter-trail.png'),
  },
} as const;
