// Static requires keep Metro/Expo asset discovery predictable.
export const wordMaizeAssets = {
  corn: {
    core: require('./corn/cob-core.png'),
    fullV2: require('./corn/cob-full-v2.png'),
    huskLeft: require('./corn/husk-left.png'),
    huskRight: require('./corn/husk-right.png'),
    huskBottom: require('./corn/husk-bottom.png'),
  },
  kernels: {
    approvedNormal: require('./corn/asset-set-v1/kernel-full.png'),
    approvedSocket: require('./corn/asset-set-v1/kernel-empty-socket.png'),
    normal: [
      require('./kernels/yellow/kernel-normal-01.png'),
      require('./kernels/yellow/kernel-normal-02.png'),
      require('./kernels/yellow/kernel-normal-03.png'),
    ],
    normalV2: require('./kernels/yellow/kernel-normal-v2.png'),
    kernelV3: require('./kernels/kernel-v3.jpg'),
    selected: require('./kernels/yellow/kernel-selected.png'),
    selectedV2: require('./kernels/yellow/kernel-selected-v2.png'),
    hint: require('./kernels/yellow/kernel-hint.png'),
    hintV2: require('./kernels/yellow/kernel-hint-v2.png'),
    emptySocket: require('./kernels/yellow/kernel-empty-socket.png'),
    emptySocketV2: require('./kernels/yellow/kernel-empty-socket-v2.png'),
    flying: require('./kernels/yellow/kernel-flying.png'),
  },
  props: {
    harvestBasket: require('./props/harvest-basket-v2.png'),
    tractor: require('./props/tractor-mascot.png'),
    chest: require('./props/golden-chest.png'),
  },
  characters: {
    patchSpeaking: require('./characters/patch-speaking-v1.png'),
  },
  powerups: {
    scarecrow: require('./powerups/scarecrow.png'),
    butterBrush: require('./powerups/butter-brush.png'),
    cornPicker: require('./powerups/corn-picker.png'),
  },
  obstacles: {
    caterpillar: require('./obstacles/caterpillar-v1.png'),
    crow: require('./obstacles/crow-v1.png'),
    squirrel: require('./obstacles/squirrel-v1.png'),
    weed: require('./obstacles/weed-v1.png'),
  },
  backgrounds: {
    gameplayFarm: require('./backgrounds/gameplay-farm.png'),
    gameplayFarmV2: require('./backgrounds/gameplay-farm-v2.png'),
    gameplayFarmV3: require('./backgrounds/gameplay_bg_v3.jpg'),
    gameplayFarmV4: require('./backgrounds/gameplay_bg_v4.jpg'),
    gameplayFarmV6: require('./backgrounds/gameplay_bg_v6.jpg'),
    gameplayFarmV7: require('./backgrounds/gameplay_bg_v7.jpg'),
    gameplayFarmV8: require('./backgrounds/gameplay_bg_v8.jpg'),
    gameplayCrowCreek: require('./backgrounds/gameplay-crow-creek-v1.png'),
    gameplayOrchardHollow: require('./backgrounds/gameplay-orchard-hollow-v1.png'),
    gameplayMoonlightMaize: require('./backgrounds/gameplay-moonlight-maize-v1.png'),
    homeFarm: require('./backgrounds/home-farm.png'),
    worldMap: require('./backgrounds/world-map.png'),
    shopBarn: require('./backgrounds/shop-barn.png'),
  },
  ui: {
    btnHome: require('./ui/btn_home.jpg'),
    btnRotate: require('./ui/btn_rotate.jpg'),
    btnHeart: require('./ui/btn_heart.jpg'),
    coin: require('./ui/coin.png'),
    energy: require('./ui/energy.png'),
    logo: require('./ui/logo-v2.png'),
  },
  effects: {
    sparkleBurst: require('./effects/sparkle-burst.png'),
    kernelPop: require('./effects/kernel-pop.png'),
    butterTrail: require('./effects/butter-trail.png'),
  },
} as const;
