// Static requires keep Metro/Expo asset discovery predictable.
export const wordMaizeAssets = {
  kernels: {
    approvedNormal: require('./corn/asset-set-v1/kernel-full.png'),
    varieties: {
      sweet: {
        full: require('./corn/asset-set-v1/kernel-full.png'),
        socket: require('./corn/asset-set-v1/kernel-empty-socket.png'),
      },
      white: {
        full: require('./corn/varieties/white/kernel-full.png'),
        socket: require('./corn/varieties/white/kernel-empty-socket.png'),
      },
      flint: [
        {
          full: require('./corn/varieties/flint-red/kernel-full.png'),
          socket: require('./corn/varieties/flint-red/kernel-empty-socket.png'),
        },
        {
          full: require('./corn/varieties/flint-orange/kernel-full.png'),
          socket: require('./corn/varieties/flint-orange/kernel-empty-socket.png'),
        },
        {
          full: require('./corn/varieties/flint-blue/kernel-full.png'),
          socket: require('./corn/varieties/flint-blue/kernel-empty-socket.png'),
        },
        {
          full: require('./corn/varieties/flint-gold/kernel-full.png'),
          socket: require('./corn/varieties/flint-gold/kernel-empty-socket.png'),
        },
      ],
      flintCrack: require('./corn/varieties/flint/kernel-crack-overlay.png'),
      popcorn: {
        full: require('./corn/varieties/popcorn/kernel-full.png'),
        socket: require('./corn/varieties/popcorn/kernel-empty-socket.png'),
      },
      blue: {
        full: require('./corn/varieties/blue/kernel-full-v2.png'),
        socket: require('./corn/varieties/blue/kernel-empty-socket.png'),
      },
      golden: {
        full: require('./corn/varieties/golden/kernel-full.png'),
        socket: require('./corn/varieties/golden/kernel-empty-socket.png'),
      },
    },
  },
  props: {
    harvestBasketEmpty: require('./props/harvest-basket-empty.png'),
    harvestBasketPartial: require('./props/harvest-basket-partial.png'),
    harvestBasketFull: require('./props/harvest-basket-full.png'),
    tractorCelebration: require('./props/tractor-celebration.png'),
    chest: require('./props/golden-chest.png'),
  },
  characters: {
    patchSpeaking: require('./characters/patch-speaking-v1.png'),
    patchPointing: require('./characters/patch-pointing.png'),
    patchWorried: require('./characters/patch-worried.png'),
    patchCelebrating: require('./characters/patch-celebrating.png'),
    farmerMayWelcome: require('./characters/farmer-may-welcome.png'),
    farmerMayCelebration: require('./characters/farmer-may-celebration.png'),
    homeFarmerIdle: require('./characters/home-farmer-idle.png'),
  },
  powerups: {
    scarecrow: require('./powerups/scarecrow.png'),
    butterBrush: require('./powerups/butter-brush.png'),
    cornPicker: require('./powerups/corn-picker.png'),
    mower: require('./powerups/mower.png'),
    tractor: require('./powerups/tractor.png'),
    lantern: require('./powerups/lantern.png'),
    raincoat: require('./powerups/raincoat.png'),
    huskClip: require('./powerups/husk-clip.png'),
  },
  obstacles: {
    caterpillar: require('./obstacles/caterpillar-kernel-v2.png'),
    crow: require('./obstacles/crow-circling-v2.png'),
    squirrel: require('./obstacles/squirrel-v1.png'),
    weed: require('./obstacles/weed-kernel-v2.png'),
    crowTarget: require('./obstacles/crow-target-v1.png'),
    web: require('./obstacles/spider-web-cluster-v1.png'),
    frost: require('./obstacles/frost-kernel-v1.png'),
    frostKernel: require('./obstacles/frost-kernel-v1.png'),
  },
  backgrounds: {
    gameplayCobByType: {
      sweet: require('./backgrounds/gameplay-cob-sweet-v1.jpg'),
      white: require('./backgrounds/corn/gameplay-cob-white-v1.png'),
      flint: require('./backgrounds/corn/gameplay-cob-flint-v1.png'),
      popcorn: require('./backgrounds/corn/gameplay-cob-popcorn-v1.png'),
      blue: require('./backgrounds/corn/gameplay-cob-blue-v2.png'),
      golden: require('./backgrounds/corn/gameplay-cob-golden-v1.png'),
    },
    mapSweetCorn: require('./backgrounds/map-sweet-corn-v1.png'),
    mapCrowCreek: require('./backgrounds/map-crow-creek-v1.png'),
    mapOrchardHollow: require('./backgrounds/map-orchard-hollow-v1.png'),
    mapMoonlight: require('./backgrounds/map-moonlight-v1.png'),
    homeFarm: require('./backgrounds/home-farm.png'),
    homeFarmRestored: require('./backgrounds/home-farm-restored.png'),
    homeHero: require('./backgrounds/home-hero-v1.jpg'),
    shopBarn: require('./backgrounds/shop-barn.png'),
  },
  ui: {
    btnRotate: require('./ui/btn-rotate.png'),
    btnPause: require('./ui/btn-pause.png'),
    btnShuffle: require('./ui/btn-shuffle.png'),
    mapNodeCurrent: require('./ui/map-node-current.png'),
    mapNodeComplete: require('./ui/map-node-complete.png'),
    mapNodeLocked: require('./ui/map-node-locked.png'),
    mapStarEmpty: require('./ui/map-star-empty.png'),
    mapStarFilled: require('./ui/map-star-filled.png'),
    tabPlay: require('./ui/tab-play.png'),
    tabShop: require('./ui/tab-shop.png'),
    tabProfile: require('./ui/tab-profile.png'),
    storeFeature: require('./ui/store-feature.png'),
    coin: require('./ui/coin-v2.png'),
    energy: require('./ui/energy.png'),
    logo: require('./ui/logo-v2.png'),
    logoTaglinePlaque: require('./ui/logo-tagline-plaque.png'),
    homeContinueThumb: require('./ui/home-continue-thumb.png'),
    homeWorldMapThumb: require('./ui/home-world-map-thumb.png'),
    homeWorldThumb: require('./ui/home-world-thumb.png'),
    iconGamepad: require('./ui/icon-gamepad.png'),
    iconFairTent: require('./ui/icon-fair-tent.png'),
    onboardingMaize: require('./ui/onboarding-ways-maize.png'),
    onboardingFair: require('./ui/onboarding-ways-fair.png'),
    iconHudTime: require('./ui/icon-hud-time.png'),
    iconHudHarvest: require('./ui/icon-hud-harvest.png'),
    iconHudChapter: require('./ui/icon-hud-chapter.png'),
    iconHudFog: require('./ui/icon-hud-fog.png'),
    chapterThumbs: [
      require('./ui/chapter-thumb-01.png'),
      require('./ui/chapter-thumb-02.png'),
      require('./ui/chapter-thumb-03.png'),
      require('./ui/chapter-thumb-04.png'),
      require('./ui/chapter-thumb-05.png'),
      require('./ui/chapter-thumb-06.png'),
      require('./ui/chapter-thumb-07.png'),
      require('./ui/chapter-thumb-08.png'),
    ],
    materials: {
      woodPlanks: require('./ui/materials/wood-planks-tile-v1.png'),
    },
  },
  effects: {
    sparkleBurst: require('./effects/sparkle-burst.png'),
  },
  fair: {
    popAWord: {
      bucket: require('../fair/pop-a-word/bucket.png'),
      popcorn: require('../fair/pop-a-word/popcorn.png'),
    },
  },
} as const;
